name: Gekoze-cicd-naam
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Clone repo
          uses: actions/checkout@v4
        - name: Install dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: "10.0.x"
        - name: Build app
          run: dotnet build src/PG3CICDSolution.slnx
        - name: Test app
          run: dotnet test src/PG3CiCd.Tests/PG3CiCd.Tests.csproj
        - name: Publish
          run: dotnet publish src/PG3CiCd/PG3CiCd.csproj -o ${{ github.workspace }}/publish 
        - name: Deploy
          uses: azure/webapps-deploy@v3
          with:
            app-name: "pg3-cicd-demo" 
            publish-profile: ${{ secrets.AZ_PUBLISH_PROFILE }} 
            package: ${{ github.workspace }}/publish          