name: Gekoze-cicd-naam
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Clone repo
          uses: actions/checkout@v4
        - name: Install dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: "10.0.x"
        - name: Build app
          run: dotnet build src/PG3CiCd/PG3CiCd.csproj